### ISSUE TITLE
Refactor de los branches

### ISSUE THREAD

**Issue by SolSerki** [MiguelSerki/TP3#5]
Voy a mergear las cosas que tenemos al master para borrar las branches y rehacerlas por funcionalidad. 
Me parece mas ordenado que por capa. 

Decime si te parece bien y le doy.

**Comment by SolSerki** [comment]
Listo, ahora hay un branch Dev donde esta la ultima versión del Master. Desde Dev sacamos branches para cada funcionalidad nueva, y la mergeamos en Dev para despues pasarla al Master si esta todo Ok y no se va a cambiar mas.

**Comment by AgustinBiglieri** [comment]
Listo, voy a arrancar desde dev entonces, cualquier duda te consulto
